### PR TITLE
Added defz.bzl shortcuts for Vulkan SDK

### PR DESCRIPTION
**Pull request by Morfly**
**What is this PR about?**
If the user wants to add a Vulkan SDK as a dependency to the target they must declare `config_settings` as in [this example](https://github.com/jadarve/rules_vulkan/blob/main/examples/BUILD).

In addition, it is required to write a platform `select` statements for `deps` and `linkopts` each time as in [this example](https://github.com/jadarve/rules_vulkan/blob/main/examples/bin/BUILD).

**What's changed?**
With this update the Vulkan SDK can be added as a dependency to the target the following way:

Root BUILD
```BUILD
load("@rules_vulkan//vulkan:defs.bzl", "vulkan_sdk")

vulkan_sdk()
```

BUILD file with cc target:
```BUILD
cc_binary(
    name = "main",
    srcs = glob(["*.cpp"]),
    deps = ["//:vulkan",],
)
```

<hr>

Alternatively, it is possible to import `VULKAN_LINKOPTS` and `VULKAN_LIBRARIES` separately.

BUILD file with cc target:
```BUILD
load("@rules_vulkan//vulkan:defs.bzl", "VULKAN_LINKOPTS", "VULKAN_LIBRARIES")

cc_binary(
    name = "main",
    srcs = glob(["*.cpp"]),
    linkopts = VULKAN_LINKOPTS,
    deps = VULKAN_LIBRARIES,
)

```

### CODE REVIEW

**Comment by jadarve** [comment]
I understand the logic. But perhaps there is a way simpler to the end-user:

Instead of asking the user to put this in their main `BUILD` file:

```python
load("@rules_vulkan//vulkan:defs.bzl", "vulkan_sdk")
vulkan_sdk()
```

we could modify the platform-specific library definitions (Linux, Mac, Windows) to:

* `vulkan_linux_cc_library`
* `vulkan_windows_cc_library`
* `vulkan_macos_cc_library`

And then create a wrapper `vulkan_cc_library` target as the one you defined

```python
cc_library(
    # renamed to vulkan_cc_library
    name = "vulkan_cc_library",
    deps = VULKAN_LIBRARIES,
    linkopts = VULKAN_LINKOPTS,
    visibility = ["//visibility:public"],
)
```

That way, any target will simply add:

```python
cc_binary(
    name = "main",
    srcs = glob(["*.cpp"]),
    deps = ["@vulkan//:vulkan_cc_library"]
)
```

Would that work?

**Comment by Morfly** [comment]
I see your point, it makes sense. 
To be honest, I'm also not a 100% fan of adding something to the root BUILD file.
 _Just for context, it was inspired by [Dagger 2](https://github.com/google/dagger), a dependency injection tool for Java, where they have similar `dagger_rules` macro._

I've added an alternate approach by updating a `vulkan/BUILD` file. An example project in `bin` directory uses `@rules_vulkan//vulkan:sdk` as a dependency. Is it something you had in mind? (naming is not final, just for example).

The idea looks good to me. The only thing that might be controversial is that we need to take a Vulkan SDK from something called `@rules_vulkan`. Of course, we might call it just `@vulkan` but would it go against the convention? (I would not mind breaking it in this case). 
In the case of renaming to `@vulkan`, some internal components of the repo would also require an update (such as `load` statements in `vulkan/repositories.bzl` file.

Overall, both options are fine to me. Let me know your thoughts. 
I will make this PR a draft for now.

**Comment by jadarve** [comment]
Hi, sorry for the late reply.

About this option:

```python
cc_binary(
    name = "list_extensions",
    srcs = ["list_extensions.cpp"],
    visibility = ["//visibility:public"],
    deps = ["@rules_vulkan//vulkan:sdk"],
)
```

I think we should preserve the `cc_library` suffix for the dependency. Calling a single `cc_library` as SDK might be overkill here.

```python
cc_binary(
    name = "list_extensions",
    srcs = ["list_extensions.cpp"],
    visibility = ["//visibility:public"],
    deps = ["@rules_vulkan//vulkan:vulkan_cc_library"],
)
```

If that's OK, then the `vulkan/BUILD` file would be the merge of your current BUILD file plus de symbols in `vulkan/defs.bzl` without the macro, something lke:

```python
load("@rules_cc//cc:defs.bzl", "cc_library")

VULKAN_LINKOPTS = select({
    "@bazel_tools//src/conditions:linux_x86_64": ["-lvulkan"],
    "//conditions:default": [],
})

VULKAN_LIBRARIES = select({
    "@bazel_tools//src/conditions:windows": ["@vulkan_windows//:vulkan_cc_library"],
    "@bazel_tools//src/conditions:darwin": ["@vulkan_macos//:vulkan_cc_library"],
    "//conditions:default": [],
})

# end users will use this definition as deps in their targets.
cc_library(
    name = "vulkan_cc_library",
    linkopts = VULKAN_LINKOPTS,
    visibility = ["//visibility:public"],
    deps = VULKAN_LIBRARIES,
)
```

What do you think?

**Comment by Morfly** [comment]
Sounds good. I've updated the PR.
Also, changed `linux_x86_64` with `linux` in `VULKAN_LINKOPTS`.

**Pull request merged**
